import { Component, signal } from '@angular/core';

import {
  AccordionContent,
  AccordionGroup,
  AccordionPanel,
  AccordionTrigger,
  BuiAccordion,
  BuiAccordionContent,
  BuiAccordionItem,
  BuiAccordionTrigger,
  BuiAlert,
  BuiAlertDescription,
  BuiAlertTitle,
  BuiAvatar,
  BuiBadge,
  BuiButton,
  BuiCard,
  BuiCardAction,
  BuiCardContent,
  BuiCardDescription,
  BuiCardFooter,
  BuiCardHeader,
  BuiCardTitle,
  BuiCheckbox,
  BuiInput,
  BuiLabel,
  BuiProgress,
  BuiSeparator,
  BuiSkeleton,
  BuiSwitch,
  BuiTabList,
  BuiTabPanel,
  BuiTabs,
  BuiTabTrigger,
  BuiTextarea,
  BuiThemeCustomizer,
  Tab,
  TabContent,
  TabList,
  TabPanel,
  Tabs,
} from 'ng-blatui';

@Component({
  selector: 'app-root',
  imports: [
    BuiButton,
    BuiBadge,
    BuiLabel,
    BuiSeparator,
    BuiSkeleton,
    BuiCard,
    BuiCardHeader,
    BuiCardTitle,
    BuiCardDescription,
    BuiCardContent,
    BuiCardFooter,
    BuiCardAction,
    BuiAlert,
    BuiAlertTitle,
    BuiAlertDescription,
    BuiInput,
    BuiTextarea,
    BuiAvatar,
    BuiProgress,
    BuiCheckbox,
    BuiSwitch,
    AccordionGroup,
    AccordionTrigger,
    AccordionPanel,
    AccordionContent,
    BuiAccordion,
    BuiAccordionItem,
    BuiAccordionTrigger,
    BuiAccordionContent,
    Tabs,
    TabList,
    Tab,
    TabPanel,
    TabContent,
    BuiTabs,
    BuiTabList,
    BuiTabTrigger,
    BuiTabPanel,
    BuiThemeCustomizer,
  ],
  templateUrl: './app.html',
  styleUrl: './app.css',
})
export class App {
  protected readonly terms = signal(true);
  protected readonly newsletter = signal(false);
  protected readonly notifications = signal(true);
}
