/**
 * Component categories — mirrors BlatUI's config/docs.php `categories`.
 * Drives the docs sidebar grouping and the /components gallery, exactly like BlatUI.
 * Keys are category labels; values are ordered component slugs.
 */
export const CATEGORIES: readonly { label: string; slugs: readonly string[] }[] = [
  {
    label: 'Forms & Input',
    slugs: [
      'button',
      'button-group',
      'copy-button',
      'input',
      'input-group',
      'input-mask',
      'input-otp',
      'number-input',
      'knob',
      'phone-input',
      'textarea',
      'autosize-textarea',
      'rich-text-editor',
      'markdown-editor',
      'label',
      'field',
      'repeater',
      'checkbox',
      'radio-group',
      'switch',
      'segmented-control',
      'select',
      'combobox',
      'autocomplete',
      'tags-input',
      'mention-input',
      'signature-pad',
      'slider',
      'toggle',
      'toggle-group',
      'rating',
      'color-picker',
      'password-strength',
      'file-upload',
      'editable',
      'calendar',
      'date-picker',
      'datetime-picker',
      'time-field',
    ],
  },
  {
    label: 'Layout',
    slugs: [
      'container',
      'stack',
      'card',
      'bento-grid',
      'page-header',
      'aspect-ratio',
      'separator',
      'scroll-area',
      'resizable',
      'sidebar',
      'accent',
      'visually-hidden',
    ],
  },
  {
    label: 'Data Display',
    slugs: [
      'avatar',
      'avatar-group',
      'presence',
      'badge',
      'table',
      'comparison-table',
      'data-table',
      'tree-table',
      'description-list',
      'carousel',
      'masonry',
      'comparison-slider',
      'chart',
      'sparkline',
      'stat',
      'meter',
      'heatmap',
      'gantt',
      'scheduler',
      'org-chart',
      'icon',
      'item',
      'kbd',
      'marquee',
      'typewriter',
      'text-reveal',
      'quote',
      'progress',
      'countdown',
      'timeline',
      'kanban',
      'tree',
      'json-viewer',
      'diff-viewer',
      'skeleton',
      'code-block',
      'typography',
    ],
  },
  {
    label: 'AI',
    slugs: [
      'chat',
      'prompt-input',
      'streaming-text',
      'reasoning',
      'tool-call',
      'citation',
      'terminal',
    ],
  },
  {
    label: 'Feedback',
    slugs: [
      'alert',
      'banner',
      'empty',
      'spinner',
      'loading-overlay',
      'top-progress',
      'sonner',
      'tooltip',
      'hover-card',
      'cookie-consent',
    ],
  },
  {
    label: 'Overlays',
    slugs: [
      'dialog',
      'alert-dialog',
      'sheet',
      'drawer',
      'popover',
      'dropdown-menu',
      'context-menu',
      'menubar',
      'command',
      'command-dialog',
      'notification-center',
      'onboarding-tour',
    ],
  },
  {
    label: 'Navigation',
    slugs: [
      'breadcrumb',
      'link',
      'tabs',
      'navigation-menu',
      'pagination',
      'stepper',
      'scrollspy',
      'bottom-navigation',
      'dock',
      'speed-dial',
      'back-to-top',
      'infinite-scroll',
    ],
  },
  {
    label: 'Disclosure',
    slugs: ['accordion', 'collapsible'],
  },
  {
    label: 'E-commerce',
    slugs: [
      'product-card',
      'price',
      'quantity-selector',
      'variant-selector',
      'add-to-cart',
      'mini-cart',
    ],
  },
  {
    label: 'Effects',
    slugs: [
      'gradient-text',
      'number-ticker',
      'border-beam',
      'spotlight-card',
      'tilt-card',
      'flip-card',
      'confetti',
      'meteors',
      'animated-beam',
      'parallax',
      'dot-pattern',
      'grid-pattern',
      'aurora',
    ],
  },
  {
    label: 'Media',
    slugs: ['audio-player', 'video', 'image', 'gallery', 'qr-code', 'map'],
  },
];

/** Display-name overrides for slugs whose humanized form is wrong (acronyms, etc.). */
export const LABEL_OVERRIDES: Readonly<Record<string, string>> = {
  'input-otp': 'Input OTP',
  'datetime-picker': 'Date & Time Picker',
  'json-viewer': 'JSON Viewer',
  'qr-code': 'QR Code',
};

/** Title-case a slug, applying overrides. */
export function labelFor(slug: string): string {
  return (
    LABEL_OVERRIDES[slug] ??
    slug
      .split('-')
      .map((part) => part.charAt(0).toUpperCase() + part.slice(1))
      .join(' ')
  );
}
